name: Build and deploy Python app to Azure Web App - familyreunionapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libjpeg-dev zlib1g-dev libtiff5-dev libfreetype6-dev \
                                  liblcms2-dev libwebp-dev tcl-dev tk-dev imagemagick

      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install Python dependencies
        run: |
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Zip artifact for deployment
        run: zip -r release.zip -x "venv/*" # This line was corrected

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9C5C2CD98B9F4B42ADE072BEF0DA633A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9B59CBC3A05F4F3B8D8C428AABF40825 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_27F2A77CF2264D80B9BFAD98A99C8A86 }}

      - name: Install libjpeg62-turbo-dev
        run: |
          sudo apt-get update
          sudo apt-get install -y libjpeg62-turbo-dev 

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'familyreunionapp'
          slot-name: 'Production'
          package:.

      - name: Set Startup Command in Azure
        run: |
          az webapp config set --name familyreunionapp --resource-group FamilyReunion \
            --startup-file "gunicorn -w 4 -b 0.0.0.0:8000 app:app"

      - name: Enable Application Logging
        run: |
          az webapp log config --name familyreunionapp --resource-group FamilyReunion \
            --application-logging filesystem --level error

      - name: Restart Azure Web App
        run: az webapp restart --name familyreunionapp --resource-group FamilyReunion

      - name: Pause to Allow App Restart
        run: |
          echo "Pausing for 30 seconds to allow the app to restart..."
          sleep 30

      - name: Stream Logs (Optional Debugging)
        run: az webapp log tail --name familyreunionapp --resource-group FamilyReunion